tried to add ModbusGateway
symcon/SymconStubs pull request #19
Opened 2019-12-14 07:57 UTC by Brovning

Hello,
I'm struggled with adding a ModbusGateway to test my module.
How can I stub a ModbusGateway?
Who is able to help here?

2019-12-14 08:17 UTC, Brovning commented
Was ist beim Test hier falsch gelaufen?
====
2019-12-14T07:58:00.0423001Z ##[error]The input 'submodules' is not supported in actions/checkout@v2
2019-12-14T07:58:00.0439425Z ##[error]Node run failed with exit code 1
===

2020-01-03 20:38 UTC, paresy commented
Sorry für die späte Antwort. GitHub hab bei den Actions etwas geändert und deswegen waren die nicht mehr korrekt. Wenn du deinen Branch einmal vom Master aktualisierst sollte alles wieder gehen.

PS: Modbus Gateway ist eine Splitter. Ggf. wäre ein SplitterStubs Ordner sinnvoll.

2020-01-03 20:42 UTC, paresy requested changes

2020-01-03 20:42 UTC, paresy commented on IOStubs/ModbusGateway/module.json
> +{
Die Infos sind hier nicht ganz korrekt. Magst du mit IPS_GetModule die "echten" Werte mal ermitteln?

2020-01-03 20:42 UTC, paresy commented on IOStubs/ModbusGateway/module.php
> +class ModBusGateway extends VirtualIO
Ich bin mir nicht sicher ob es gut ist vom VirtualIO zu erben. Was wäre der Vorteil?

2020-01-03 20:42 UTC, paresy commented on IOStubs/ModbusGateway/module.php
> +        $this->RegisterPropertyBoolean('SwapWords', false);
Default ist hier true

2020-01-04 19:19 UTC, Brovning commented
> GitHub hab bei den Actions etwas geändert und deswegen waren die nicht mehr korrekt. Wenn du deinen Branch einmal vom Master aktualisierst sollte alles wieder gehen.
Sorry für die doofe Frage, aber wie mache ich das Update des Forks auf den aktuellen Stand des Masters?

2020-01-04 19:23 UTC, Brovning commented on IOStubs/ModbusGateway/module.php
> +class ModBusGateway extends VirtualIO
Keine Ahnung. Was schlägst du vor?

2020-01-07 12:27 UTC, paresy requested changes

2020-01-07 12:27 UTC, paresy commented on IOStubs/ModbusGateway/module.php
> +class ModBusGateway extends VirtualIO
Wenn du nicht von den Funktionen des VirtualIO nutzt kannst du direkt von IPSModule erben.

2020-01-07 12:28 UTC, paresy commented
> > GitHub hab bei den Actions etwas geändert und deswegen waren die nicht mehr korrekt. Wenn du deinen Branch einmal vom Master aktualisierst sollte alles wieder gehen.
> 
> Sorry für die doofe Frage, aber wie mache ich das Update des Forks auf den aktuellen Stand des Masters?

Welches Tool nutzt du denn? Im Prinzip willst du ein "git pull master" machen

2020-01-07 18:43 UTC, Brovning commented on IOStubs/ModbusGateway/module.php
> +class ModBusGateway extends VirtualIO
done

2020-01-07 18:47 UTC, Brovning commented
> > > GitHub hab bei den Actions etwas geändert und deswegen waren die nicht mehr korrekt. Wenn du deinen Branch einmal vom Master aktualisierst sollte alles wieder gehen.
> > 
> > 
> > Sorry für die doofe Frage, aber wie mache ich das Update des Forks auf den aktuellen Stand des Masters?
> 
> Welches Tool nutzt du denn? Im Prinzip willst du ein "git pull master" machen

Ich nutze GitHub Desktop für Windows.
Aktuell habe ich einen Fork auf meiner Festplatte mit meiner Änderung.
Was müsste ich im Command Promt ausführen, um den Rest wieder mit dem Master von SymconStubs zu resynchronisieren?

2020-03-29 14:49 UTC, paresy approved these changes
Magst du wie oben vorgeschlagen noch das Modul in einen SplitterStubs Ordner verschieben?

2020-03-29 14:49 UTC, paresy commented on IOStubs/ModbusGateway/module.json
> +	"name": "Modbus Gateway",
MudBus <-- B groß

2020-03-29 14:49 UTC, paresy commented on IOStubs/ModbusGateway/module.json
> +	"prefix": "MBGT"
ModBus

2020-03-29 14:49 UTC, paresy commented on IOStubs/ModbusGateway/module.php
> +include_once __DIR__ . '/../VirtualIO/module.php';
Kann weg, da wir von IPSModule erben

2020-03-29 14:50 UTC, paresy requested changes
Hatte mich verklickt und den Status falsch gesetzt :-)

2020-04-08 14:41 UTC, paresy commented
Ich würde hier erstmal schließen. Mach gerne wieder auf, sobald du noch einmal Zeit dafür hast :-)

2020-04-08 14:41 UTC, closed without merging